[env:bluepill]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; Core libmaple (Roger Clark) — obrigatório para a classe USB MIDI
board_build.core = maple

; Gravação via ST-Link V2 (SWD)
upload_protocol = stlink

lib_deps =
    arpruss/USBComposite for STM32F1

; A porta USB é composta: MIDI class-compliant + CDC serial simultâneos
